Fixed compilation errors due to changes in WSDL definitions.
git-svn-id: http://escidev5.fiz-karlsruhe.de:8888/prototype/branches/eSciDocCoreClient/1.2/eSciDocCoreClient-rest/eSciDocCoreClient/@38001 5c398c58-3d0a-0410-a38c-d0825f6816e0